M48
; DRILL file {KiCad 9.0.4} date 2025-10-16T13:30:43+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-16T13:30:43+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X135.2Y-79.765
X147.2Y-79.765
T2
X174.2Y-62.195
X174.2Y-117.805
M30
